/** Languages we can parse right now. */
export type Language = "javascript" | "typescript" | "tsx" | "python" | "java" | "go";

/** A source file found while walking the repo, before it's parsed. */
export interface SourceFile {
  /** Repo-relative path, always with forward slashes. */
  path: string;
  /** Absolute path on disk. */
  absPath: string;
  language: Language;
  sizeBytes: number;
}

/** A function, method or class declared in a file. */
export interface FunctionSymbol {
  /** Stable id, `<file path>#<qualified name>`. */
  id: string;
  name: string;
  /** Dotted name for nested declarations, like `MyClass.render`. */
  qualifiedName: string;
  kind: "function" | "method" | "class";
  startLine: number;
  endLine: number;
  exported: boolean;
  /** 0..1 score from the function-level call graph. */
  importance: number;
  /**
   * One-line summary from the LLM. Only set for the top functions of summarised files.
   */
  summary?: string;
}

/** A file in the dependency graph. */
export interface FileNode {
  /** Same as `path`. */
  id: string;
  path: string;
  type: "file";
  language: Language;
  /** Centrality and churn blended into one 0..1 score. */
  importance: number;
  metrics: FileMetrics;
  /** 1-3 sentence summary from the LLM, if this file got summarised. */
  summary?: string;
  /**
   * Ids of this file's declarations. The actual records live in
   * `RepoGraph.functionNodes`.
   *
   * These used to be full objects, so every declaration got written out twice. On an
   * 18,851-file repo that was 32MB of duplicates. Use `functionIndex()` / `functionsOf()`
   * to look them up.
   */
  functions: string[];
}

export interface FileMetrics {
  /** Raw line count. */
  loc: number;
  /** How many commits touched this file. */
  churn: number;
  /** How many files this one imports. */
  outDegree: number;
  /** How many files import this one. */
  inDegree: number;
  /** The centrality half of `importance`, 0..1. */
  centrality: number;
  /** The churn half of `importance`, 0..1. */
  churnScore: number;
}

export interface GraphEdge {
  from: string;
  to: string;
  type: "import" | "call";
  /** How many times we saw this relationship. */
  weight: number;
}

/**
 * A declaration in the function-level graph. This is the one real copy;
 * `FileNode.functions` just points here by id.
 */
export interface FunctionNode {
  id: string;
  /** Path of the file it lives in. */
  file: string;
  name: string;
  qualifiedName: string;
  kind: FunctionSymbol["kind"];
  type: "function";
  importance: number;
  startLine: number;
  endLine: number;
  /** Whether the module exports it. */
  exported: boolean;
  summary?: string;
}

/**
 * Repo details from GitHub (description, stars and so on). Only there when the repo is on
 * GitHub and the lookup worked.
 */
export interface RepositoryInfo {
  host: "github.com";
  owner: string;
  name: string;
  /** `owner/name`, spelled the way GitHub spells it. */
  fullName: string;
  /** The repo's GitHub page. */
  url: string;
  description?: string;
  homepage?: string;
  stars?: number;
  forks?: number;
  /** Main language according to GitHub. */
  language?: string;
  topics?: string[];
  /** SPDX id, e.g. "MIT". */
  license?: string;
  defaultBranch?: string;
  /** Last push to the repo. */
  pushedAt?: string;
  archived?: boolean;
  private?: boolean;
  /** When we fetched this. It goes stale. */
  fetchedAt: string;
}

export interface RepoGraph {
  /**
   * Version 2: `nodes[].functions` holds ids into `functionNodes` instead of copies.
   * Version 1 files have the old duplicated shape and need regenerating.
   */
  version: 2;
  /** Where the source came from. For clones, the original URL. */
  source: string;
  generatedAt: string;
  stats: GraphStats;
  nodes: FileNode[];
  edges: GraphEdge[];
  functionNodes: FunctionNode[];
  functionEdges: GraphEdge[];
  /** GitHub's details for the repo, if it's on GitHub. */
  repository?: RepositoryInfo;
  /** Set whenever we tried to summarise, even if it got skipped. */
  summarization?: SummarizationReport;
  /** Which files make up `stats.parseFailures`, so a regression is easy to track down. */
  parseFailures: ParseFailure[];
}

/** What happened in the summarise step, so the CLI can report it straight. */
export interface SummarizationReport {
  /** False if summarising couldn't run at all. `message` says why. */
  ran: boolean;
  model: string;
  /** Files picked for summarising. */
  selected: number;
  /** Reused from .synapse/summaries.json since the file hadn't changed. */
  fromCache: number;
  /** Newly generated by the model. */
  generated: number;
  /** Files that failed to summarise. They just don't get a summary. */
  failed: number;
  /** Set when the step was skipped or partly failed, with what to do about it. */
  message?: string;
}

/** A file we couldn't read or parse, so it's missing from the graph. */
export interface ParseFailure {
  path: string;
  /** The read or parse error, word for word. */
  reason: string;
}

export interface GraphStats {
  fileCount: number;
  edgeCount: number;
  functionCount: number;
  functionEdgeCount: number;
  /** Imports that point outside the repo (node_modules, stdlib, or just unresolved). */
  externalImports: number;
  /**
   * Files that failed to read or parse and so aren't in the graph. Should be zero.
   * Anything else means the graph is incomplete and every score is based on a partial
   * picture.
   */
  parseFailures: number;
  byLanguage: Record<string, number>;
  /** True if we had git history and could measure churn. */
  churnAvailable: boolean;
}
