/** Languages we can currently parse. */
export type Language = "javascript" | "typescript" | "tsx" | "python";

/** A source file discovered during ingestion, before parsing. */
export interface SourceFile {
  /** Path relative to the repo root, always POSIX-separated. */
  path: string;
  /** Absolute path on disk. */
  absPath: string;
  language: Language;
  sizeBytes: number;
}

/** A function, method, or class declaration found inside a file. */
export interface FunctionSymbol {
  /** Stable id: `<file path>#<qualified name>`. */
  id: string;
  name: string;
  /** Dotted path for nested declarations, e.g. `MyClass.render`. */
  qualifiedName: string;
  kind: "function" | "method" | "class";
  startLine: number;
  endLine: number;
  exported: boolean;
  /** Centrality-derived score within the function-level graph, 0..1. */
  importance: number;
  /** One-sentence LLM summary. Present only for summarised files' top functions. */
  summary?: string;
}

/** A file-level node in the dependency graph. */
export interface FileNode {
  /** Stable id; identical to `path`. */
  id: string;
  path: string;
  type: "file";
  language: Language;
  /** Combined centrality + churn score, normalised to 0..1. */
  importance: number;
  metrics: FileMetrics;
  /** 1-3 sentence LLM summary. Present only for files that were summarised. */
  summary?: string;
  /**
   * Ids of the declarations in this file, pointing into `RepoGraph.functionNodes`,
   * which is the single source of truth for them.
   *
   * These used to be full objects, which meant every declaration was serialised twice —
   * 32MB of pure duplication on an 18,851-file repo. Resolve them with
   * `functionIndex()` / `functionsOf()`.
   */
  functions: string[];
}

export interface FileMetrics {
  /** Lines of code (raw line count). */
  loc: number;
  /** Number of commits that touched this file. */
  churn: number;
  /** Files this file imports. */
  outDegree: number;
  /** Files that import this file. */
  inDegree: number;
  /** Normalised graph-centrality component of `importance`, 0..1. */
  centrality: number;
  /** Normalised churn component of `importance`, 0..1. */
  churnScore: number;
}

export interface GraphEdge {
  from: string;
  to: string;
  type: "import" | "call";
  /** How many times this relationship was observed. */
  weight: number;
}

/**
 * A declaration in the function-level graph, and the canonical record of it.
 *
 * `FileNode.functions` holds ids into this list rather than copies.
 */
export interface FunctionNode {
  id: string;
  /** Owning file's path. */
  file: string;
  name: string;
  qualifiedName: string;
  kind: FunctionSymbol["kind"];
  type: "function";
  importance: number;
  startLine: number;
  endLine: number;
  /** Whether the declaration is exported from its module. */
  exported: boolean;
  summary?: string;
}

export interface RepoGraph {
  /**
   * 2 — `nodes[].functions` holds ids into `functionNodes` rather than copies of the
   * declarations. A version 1 file has the duplicated shape and must be regenerated.
   */
  version: 2;
  /** Where the analysed source lived. For clones, the original URL. */
  source: string;
  generatedAt: string;
  stats: GraphStats;
  nodes: FileNode[];
  edges: GraphEdge[];
  functionNodes: FunctionNode[];
  functionEdges: GraphEdge[];
  /** Present whenever summarisation was attempted, including when it was skipped. */
  summarization?: SummarizationReport;
  /** The files behind `stats.parseFailures`, so a regression names itself. */
  parseFailures: ParseFailure[];
}

/** What happened during the summarisation pass, for the CLI to report honestly. */
export interface SummarizationReport {
  /** False when summarisation could not run at all; `message` says why. */
  ran: boolean;
  model: string;
  /** Files selected for summarisation. */
  selected: number;
  /** Reused from .synapse/summaries.json because the file had not changed. */
  fromCache: number;
  /** Freshly generated by the model. */
  generated: number;
  /** Files whose summarisation failed; they simply carry no summary. */
  failed: number;
  /** Set when the pass was skipped or partially failed, with remediation. */
  message?: string;
}

/** A file that could not be read or parsed, and so is absent from the graph. */
export interface ParseFailure {
  path: string;
  /** Why it dropped out — the read or parse error, verbatim. */
  reason: string;
}

export interface GraphStats {
  fileCount: number;
  edgeCount: number;
  functionCount: number;
  functionEdgeCount: number;
  /** Imports that pointed outside the repo (node_modules, stdlib, unresolved). */
  externalImports: number;
  /**
   * Files that failed to read or parse and are therefore missing from the graph.
   * Should be zero; anything else means the graph is incomplete and every importance
   * score is computed over a partial picture.
   */
  parseFailures: number;
  byLanguage: Record<string, number>;
  /** True when git history was available and churn was measured. */
  churnAvailable: boolean;
}
